name: shoes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  lottie: ^3.1.2
  carousel_slider: ^4.2.1
  flutter_gemini: ^2.0.5
  dash_chat_2: ^0.0.21
  sqflite: ^2.3.3+1
  path: ^1.9.0
  camera: ^0.11.0+2
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Airbnb
      fonts:
        - asset: assets/fonts/Airbnb Cereal App Black.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-color.png"
  min_sdk_android: 23
